server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flutter_book?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 4305
    driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true

mybatis:
  type-aliases-package: com.maxingg.flutter_book_backend.model
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  #configLocation: classpath:/mybatis-config.xml

# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: maxing486Secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24) -- 7天
  tokenHead: Bearer  #JWT负载中拿到开头

